const countryOptions = [
    { value: 'United States', label: 'United States', flagCode: 'US' },
    { value: 'Canada', label: 'Canada', flagCode: 'CA' },
    { value: 'United Kingdom', label: 'United Kingdom', flagCode: 'GB' },
    { value: 'Sri Lanka', label: 'Sri Lanka', flagCode: 'LK' },
    { value: 'India', label: 'India', flagCode: 'IN' },
    { value: 'Australia', label: 'Australia', flagCode: 'AU' },
    { value: 'Germany', label: 'Germany', flagCode: 'DE' },
    { value: 'France', label: 'France', flagCode: 'FR' },
    { value: 'China', label: 'China', flagCode: 'CN' },
    { value: 'Japan', label: 'Japan', flagCode: 'JP' },
    { value: 'Italy', label: 'Italy', flagCode: 'IT' },
    { value: 'Netherlands', label: 'Netherlands', flagCode: 'NL' },
    { value: 'Russia', label: 'Russia', flagCode: 'RU' },
    { value: 'Maldives', label: 'Maldives', flagCode: 'MV' },
    { value: 'Switzerland', label: 'Switzerland', flagCode: 'CH' },
    { value: 'South Korea', label: 'South Korea', flagCode: 'KR' },
    { value: 'Thailand', label: 'Thailand', flagCode: 'TH' },
    { value: 'Singapore', label: 'Singapore', flagCode: 'SG' },
    { value: 'Malaysia', label: 'Malaysia', flagCode: 'MY' },
    { value: 'Sweden', label: 'Sweden', flagCode: 'SE' },
    { value: 'Norway', label: 'Norway', flagCode: 'NO' },
    { value: 'New Zealand', label: 'New Zealand', flagCode: 'NZ' },
    { value: 'Denmark', label: 'Denmark', flagCode: 'DK' },
    { value: 'Belgium', label: 'Belgium', flagCode: 'BE' },
    { value: 'Austria', label: 'Austria', flagCode: 'AT' },
    { value: 'Saudi Arabia', label: 'Saudi Arabia', flagCode: 'SA' },
    { value: 'United Arab Emirates', label: 'United Arab Emirates', flagCode: 'AE' },
    { value: 'Qatar', label: 'Qatar', flagCode: 'QA' },
    { value: 'Ireland', label: 'Ireland', flagCode: 'IE' },
    { value: 'Finland', label: 'Finland', flagCode: 'FI' },
];

export default countryOptions;
